<?php

namespace Tests;


use PHPUnit\Framework\TestCase;
use Yahyya\FeeCalulation\Controllers\OperationController;

class UnitTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    function test_read_file()
    {
        $controller = new OperationController();
        $fees = $controller->getFees();

        $this->assertEquals(0.60,$fees[0]);
        $this->assertEquals(3.00,$fees[1]);
        $this->assertEquals(0.00,$fees[2]);
        $this->assertEquals(0.06,$fees[3]);
        $this->assertEquals(1.50,$fees[4]);
        $this->assertEquals(0,$fees[5]);
        $this->assertEquals(0.69,$fees[6]);
        $this->assertEquals(0.30,$fees[7]);
        $this->assertEquals(0.30,$fees[8]);
        $this->assertEquals(3.00,$fees[9]);
        $this->assertEquals(0.00,$fees[10]);
        $this->assertEquals(0.00,$fees[11]);
        $this->assertEquals(8612,$fees[12]);
    }
}
